export const BASE_URL = "http://localhost:5000/api/"

export const SET_COLLECTIONS_FROM_API = 'SET_COLLECTIONS_FROM_API'

export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_UPDATE_QUANTITY_ITEM = 'CART_UPDATE_QUANTITY_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_CLEAR = 'CART_CLEAR'

export const USER_LOGGIN = 'USER_LOGGIN'
export const USER_LOGOUT = 'USER_LOGOUT'